version: '3.6'
services:
    broker:
        image: rabbitmq:3.9-management
        container_name: 'rabbitmq_broker'
        ports:
            - '5672:5672'
            - '15672:15672'
        environment:
            RABBITMQ_DEFAULT_USER: "twinuser"
            RABBITMQ_DEFAULT_PASS: "twinpass"
        networks:
            - 'twinnetwork'
networks:
    twinnetwork:
        driver: bridge